Map<String, Object?> paymentAttemptJson({
  String paymentType = 'TRAVEL_GROUND_SERVICE_FEE',
  String provider = 'ALIPAY_PLUS',
  String status = 'CREATED',
  Object? nextAction,
  Object? amountMinor = 40000,
  Object? refundedAmountMinor = 0,
  Object? expiresAt = '2026-08-07T12:30:00',
}) =>
    {
      'id': 'payment-1',
      'orderId': 'order-1',
      'paymentType': paymentType,
      'provider': provider,
      'paymentMethod': 'ALIPAY_PLUS_CASHIER',
      'currency': 'USD',
      'amountMinor': amountMinor,
      'refundedAmountMinor': refundedAmountMinor,
      'status': status,
      'providerPaymentId': 'provider-payment-1',
      'failureCode': null,
      'failureMessage': null,
      'nextAction': nextAction,
      'expiresAt': expiresAt,
      'createdAt': '2026-08-07T12:00:00',
      'updatedAt': '2026-08-07T12:00:01',
    };
